# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]     # لو الفرع الأساسي master غيّرها
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm install
        # run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage (artifact اختياري)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

